"""
Math Vocabulary Bank — K-5, Common Core aligned.

Generates vocab_data.json and vocab_bank/grade-*.md from the DATA table below.
Run this, then build_html.py:

    python3 build_data.py && python3 build_html.py

Writing guidelines for this table
---------------------------------
Definitions and examples are written for the child, not about the child, and
are checked against the Flesch scale on every build (see readability.py).

* Short sentences. Sentence length is the biggest single lever on
  readability, so two plain sentences always beat one clause-stacked one.
* Everyday words around the hard word. "denominator" is five syllables and
  cannot be avoided, but everything surrounding it can be one or two.
* Examples are *situated*: a named child, a real setting, and the reasoning
  made visible - read the problem, then work it - after Polya. The Feynman
  habit of explaining a thing in plain language is the target register.
* A small recurring cast (Maya, Leo, Ana, Ben, Ivy, Zoe, Theo, Nina, Omar,
  Sam) so the bank reads as one world instead of 189 unrelated sentences.
* Misconceptions name what a child actually does wrong, not the abstract
  error.
"""
import json
import os
import re

import readability

DOMAIN_NAMES = {
    "CC": "Counting & Cardinality",
    "OA": "Operations & Algebraic Thinking",
    "NBT": "Number & Operations in Base Ten",
    "NF": "Number & Operations—Fractions",
    "MD": "Measurement & Data",
    "G": "Geometry",
}

# grade -> domain_code -> [(term, definition, example, misconception)]
DATA = {
"K": {
 "CC": [
  ("count", "Say number words in order. Touch one thing for each word you say.",
   "Maya has a bowl of grapes. She touches each one and says: 1, 2, 3, 4, 5. She counted 5 grapes.",
   "Kids often skip a number, or touch the same grape twice."),
  ("number", "A word or sign that tells how many.",
   "Leo draws 3 stars on his paper. Next to them he writes the number 3. The 3 tells how many stars are there.",
   ""),
  ("more", "A bigger amount. One group has extra.",
   "Ana has 7 stickers. Sam has 4 stickers. Ana has more, because 7 is a bigger amount than 4.",
   "Kids may think 'more' means bigger in size. A group of 7 tiny beads is still more than 4 big ones."),
  ("fewer", "A smaller amount. One group has less than the other.",
   "Ivy picks 3 apples. Ben picks 6 apples. Ivy has fewer apples than Ben.",
   "'Fewer' is for things you count one by one. 'Less' is for things you measure, like water."),
  ("equal", "The same amount. Not more and not less.",
   "Zoe has 3 red blocks. Omar has 3 blue blocks. The groups are equal. Each one has 3.",
   ""),
  ("greater than", "A bigger value than another number.",
   "Nina rolls an 8. Theo rolls a 5. Nina's number is greater than Theo's, so she moves first.",
   ""),
  ("less than", "A smaller value than another number.",
   "Sam counts 2 birds on the wire. Maya counts 9. Sam's number is less than Maya's.",
   ""),
  ("one more", "The very next number when you count up.",
   "Leo has 4 marbles. His mom hands him 1 more. Now he has 5. One more than 4 is 5.",
   ""),
  ("zero", "A number that means none at all.",
   "The cookie jar had 3 cookies. Ana's family ate every one. Now there are zero cookies left.",
   "Zero is a real number, not an empty space. It tells you the amount is none."),
  ("in order", "Lined up from smallest to biggest.",
   "Ana drops her number cards and they get mixed up. She puts them back in order: 1, 2, 3, 4, 5.",
   ""),
 ],
 "OA": [
  ("add", "Put groups together. You find how many there are in all.",
   "Ben has 2 red cars. He gets 3 blue cars. He adds them together: 2 and 3 make 5 cars.",
   ""),
  ("subtract", "Take some away. You find how many are left.",
   "Ivy has 5 balloons. Two of them pop. She subtracts 2 from 5. Now 3 balloons are left.",
   ""),
  ("sum", "The total you get when you add.",
   "Zoe finds 2 shells, then 3 more. She adds them. The sum is 5 shells.",
   "'Sum' means the answer to adding. Kids sometimes use it for any answer."),
  ("put together", "Join two groups to make one bigger group.",
   "Theo puts together 3 red blocks and 2 blue blocks. Now he has one tower of 5 blocks.",
   ""),
  ("take apart", "Split one group into smaller groups.",
   "Nina has 5 crackers. She takes them apart into a group of 2 and a group of 3.",
   ""),
  ("decompose", "Break a number into smaller parts. It is a big word for 'break apart'.",
   "Omar holds 5 pennies. He decomposes 5 into 4 and 1. He puts 4 in one hand and 1 in the other.",
   "The word sounds hard, but the job is easy. It just means breaking a number into parts."),
  ("equation", "A math sentence with an equal sign. It shows two sides that match.",
   "Maya writes 3 + 2 = 5. That is an equation. The left side and the right side are worth the same.",
   ""),
  ("in all", "Words in a problem that ask for the total.",
   "Leo has 4 toy cars. Sam has 2. How many do they have in all? The boys add and find 6.",
   ""),
  ("left", "Words in a problem that ask what is still there.",
   "Ana bakes 6 muffins and eats 2. How many are left? She subtracts and finds 4.",
   "Hunting for key words alone can trick you. Always picture what is really happening in the story."),
 ],
 "NBT": [
  ("ten", "A group of ten ones.",
   "Ben lines up 10 straws and wraps a band around them. Now he holds 1 ten.",
   ""),
  ("ones", "Single things. You count them one at a time.",
   "Ivy builds 13 with straws. She uses 1 bundle of ten, and 3 loose ones.",
   ""),
  ("teen number", "A number from 11 to 19. Each one is a ten plus some ones.",
   "Zoe counts 14 beads. 14 is a teen number. It is 1 ten and 4 ones.",
   ""),
  ("compose", "Put parts together to build a number.",
   "Theo composes 12. He takes 1 bundle of ten and adds 2 loose ones.",
   ""),
 ],
 "MD": [
  ("longer", "Goes on for more length.",
   "Nina lays her pencil beside her eraser. The pencil reaches farther, so the pencil is longer.",
   "Line up the ends first. If one thing starts ahead, the test is not fair."),
  ("shorter", "Takes up less length.",
   "Omar puts his crayon next to a ruler. The crayon stops sooner, so the crayon is shorter.",
   ""),
  ("taller", "Goes up higher.",
   "Maya stands beside a young tree. The tree rises above her head, so the tree is taller.",
   ""),
  ("heavier", "Weighs more. It pulls down harder.",
   "Leo holds a rock in one hand and a leaf in the other. The rock pulls his hand down. The rock is heavier.",
   "Big does not always mean heavy. A huge pillow weighs less than a small stone."),
  ("lighter", "Weighs less.",
   "Ana holds a feather and a book. The feather is easy to lift, so the feather is lighter.",
   ""),
  ("measure", "Find out how big, how long, or how much.",
   "Ben measures his desk with blocks. He lays them end to end with no gaps. The desk is 8 blocks long.",
   "Leave no gaps and no overlaps. Sloppy spacing gives the wrong count."),
  ("compare", "Look at two things. See how they are the same or different.",
   "Ivy compares two ribbons. She lines up the ends. The red one reaches farther, so it is longer.",
   ""),
  ("sort", "Put things in groups that go together.",
   "Zoe sorts her buttons by color. Red buttons go in one pile. Blue buttons go in another.",
   ""),
  ("category", "A group of things that share something.",
   "Theo makes a category for round things. The ball and the coin both go in it.",
   ""),
 ],
 "G": [
  ("shape", "The form of a thing. It is the outline you see.",
   "Nina traces the lid of a jar onto paper. The shape she draws is a circle.",
   ""),
  ("circle", "A round shape. It has no corners and no straight sides.",
   "Omar looks at the clock on the wall. His finger slides all the way around the face with no bumps. It is a circle.",
   ""),
  ("triangle", "A shape with 3 straight sides and 3 corners.",
   "Maya folds her napkin into a triangle. She counts 3 sides and 3 corners.",
   "A triangle can be tall, wide, or tipped over. It still counts as long as it has 3 straight sides."),
  ("square", "A shape with 4 straight sides. All 4 sides are the same length.",
   "Leo checks a sticky note against his ruler. All 4 sides match, so it is a square.",
   ""),
  ("rectangle", "A shape with 4 straight sides and 4 corners. The sides across from each other match.",
   "Ana measures the door. The two tall sides match. The two short sides match too. The door is a rectangle.",
   "A square is a rectangle too. It is just a special one with all 4 sides the same."),
  ("hexagon", "A shape with 6 straight sides.",
   "Ben studies a honeycomb up close. Each little cell has 6 sides, so each cell is a hexagon.",
   ""),
  ("cube", "A solid shape with 6 square faces.",
   "Ivy rolls a number cube. Every face she lands on is a square. She counts 6 faces in all.",
   ""),
  ("sphere", "A solid shape that is round all over, like a ball.",
   "Zoe spins a basketball on her finger. It looks round from every side. It is a sphere.",
   "A circle is flat. A sphere is solid. A plate is a circle, a marble is a sphere."),
  ("above", "Higher up than something else.",
   "Theo watches a bird land on a branch. The bird is above the grass.",
   ""),
  ("below", "Lower down than something else.",
   "Nina digs in the garden. She finds the roots growing below the soil.",
   ""),
  ("beside", "Right next to something.",
   "Omar's cat sits beside the dog. The two of them rest side by side on the rug.",
   ""),
  ("corner", "The point where two sides meet.",
   "Maya runs her finger around a square tile. She feels a sharp point at each corner and counts 4.",
   ""),
 ],
},
"1": {
 "OA": [
  ("addend", "A number you add to another number.",
   "Leo writes 3 + 4 = 7. The 3 and the 4 are the addends. They are the parts he put together.",
   "The answer is not an addend. Only the numbers going in are addends."),
  ("sum", "The answer you get when you add.",
   "Ana finds 6 shells, then 2 more. She adds them up. The sum is 8 shells.",
   ""),
  ("difference", "The answer you get when you subtract.",
   "Ben has 9 grapes and eats 4. He subtracts to find the difference. It is 5 grapes.",
   "In math, 'difference' does not mean how two things are unlike. It is the subtraction answer."),
  ("equation", "A math sentence with an equal sign. Both sides are worth the same.",
   "Ivy writes 5 + 3 = 8. Each side of the equal sign is worth 8, so the sentence balances.",
   "The equal sign does not mean 'here comes the answer'. It means both sides match."),
  ("unknown", "The missing number in a problem. You solve to find it.",
   "Zoe sees 4 + ? = 9. The ? is the unknown. She counts up from 4 to 9 and finds 5.",
   ""),
  ("fact family", "A set of facts built from the same three numbers.",
   "Theo uses 3, 4, and 7. His fact family is 3 + 4 = 7, 4 + 3 = 7, 7 - 3 = 4, and 7 - 4 = 3.",
   ""),
  ("doubles", "Adding a number to itself.",
   "Nina has 4 red beads and 4 blue beads. That is a double. She knows 4 + 4 = 8 right away.",
   ""),
  ("compare", "Look at two numbers. Tell which is bigger or smaller.",
   "Omar compares 6 and 9 on the number line. The 9 sits farther right, so 9 is bigger.",
   ""),
  ("how many more", "Words that ask about the gap between two amounts.",
   "Maya has 8 stickers. Leo has 5. How many more does Maya have? She subtracts and finds 3.",
   ""),
 ],
 "NBT": [
  ("place value", "The value a digit has because of where it sits.",
   "Ana writes 47. The 4 sits in the tens place, so it is worth 40. The 7 is worth just 7.",
   "In 47, the 4 does not mean four. Its spot makes it worth forty."),
  ("tens", "Groups of ten.",
   "Ben bundles his straws into groups of ten. He makes 3 bundles. That is 3 tens, or 30.",
   ""),
  ("ones", "Single units left over after you make tens.",
   "Ivy has 25 beads. She makes 2 bundles of ten and has 5 ones left over.",
   ""),
  ("greater than (>)", "A sign that points to the bigger number.",
   "Zoe writes 8 > 5. The wide open side faces the 8, because 8 is the greater number.",
   ""),
  ("less than (<)", "A sign that shows the first number is smaller.",
   "Theo writes 3 < 7. The narrow point faces the 3, because 3 is less.",
   "Think of a hungry mouth. It always opens toward the bigger number."),
  ("equal to (=)", "A sign that shows both sides are worth the same.",
   "Nina writes 6 = 6. Both sides match exactly, so the equal sign fits.",
   ""),
  ("count on", "Start at one number and keep counting up.",
   "Omar has 6 marbles and gets 3 more. He counts on from 6: 7, 8, 9. He has 9.",
   "Do not start over at 1. Begin at the number you already have."),
 ],
 "MD": [
  ("length", "How long something is from end to end.",
   "Maya measures her shoe with paper clips. She lays them end to end. The length is 5 clips.",
   ""),
  ("measure", "Find the size of something with a tool or a unit.",
   "Leo measures his book with cubes. He lines them up with no gaps and counts 7.",
   ""),
  ("order by length", "Line things up from shortest to longest.",
   "Ana holds three ribbons. She lines up one end of each, then orders them by length.",
   ""),
  ("hour", "A unit of time. The short hand on a clock points to it.",
   "Ben checks the clock. The short hand is on 3 and the long hand is on 12. It is 3 o'clock.",
   ""),
  ("half hour", "Thirty minutes. Half of one hour.",
   "Ivy looks at the clock. The long hand points straight down at 6. It is half past 2.",
   ""),
  ("data", "Facts you collect and can count.",
   "Zoe asks every classmate about their pet. She writes down each answer. Those answers are her data.",
   ""),
  ("tally chart", "A chart that counts with small marks.",
   "Theo makes a tally chart of bus riders. He draws one mark per rider. Every fifth mark crosses the other four.",
   ""),
  ("graph", "A picture that shows data so you can compare.",
   "Nina graphs the class pets. The dog bar is the tallest, so dogs are the most common pet.",
   ""),
 ],
 "G": [
  ("partition", "Cut a shape into parts.",
   "Omar partitions his sandwich. He cuts straight down the middle into 2 equal parts.",
   ""),
  ("equal shares", "Parts that are all the same size.",
   "Maya splits a pancake with her sister. Each one gets an equal share. Neither piece is bigger.",
   "Same number of pieces is not enough. The pieces have to be the same size too."),
  ("halves", "Two equal parts of one whole.",
   "Leo cuts an apple into halves. Each piece is one of two equal parts.",
   ""),
  ("fourths", "Four equal parts of one whole.",
   "Ana cuts a pizza into fourths. She and 3 friends each take one part.",
   ""),
  ("quarters", "Another word for fourths.",
   "Ben folds his paper in half, then in half again. He opens it up and finds 4 quarters.",
   ""),
  ("attribute", "Something you can notice about a shape, like its sides or corners.",
   "Ivy looks at a triangle. She names two attributes: 3 sides and 3 corners.",
   ""),
  ("2D shape", "A flat shape. It has length and width but no thickness.",
   "Zoe draws a square on paper. It lies flat on the page, so it is a 2D shape.",
   ""),
  ("3D shape", "A solid shape you can hold. It takes up space.",
   "Theo picks up a wooden cube. He can turn it over in his hand, so it is a 3D shape.",
   ""),
 ],
},
"2": {
 "OA": [
  ("repeated addition", "Adding the same number again and again.",
   "Nina sets out 4 plates and puts 3 grapes on each. She adds 3 + 3 + 3 + 3 and gets 12 grapes.",
   ""),
  ("array", "Objects set out in equal rows and columns.",
   "Omar lines up his stickers in 3 rows of 5. That is an array. He counts 15 stickers.",
   "Every row must hold the same amount. A ragged grid is not an array."),
  ("even number", "A number that splits into two equal groups with none left over.",
   "Maya pairs up her 8 socks. She makes 4 pairs with nothing left over, so 8 is even.",
   ""),
  ("odd number", "A number that leaves one extra when you split it in two.",
   "Leo tries to pair up 7 crackers. He makes 3 pairs and 1 is left alone, so 7 is odd.",
   ""),
  ("two-step problem", "A problem you solve in two moves.",
   "Ana has 10 pencils. She buys 5 more, then gives 3 to Ben. First she adds to get 15. Then she subtracts to get 12.",
   "Stopping after the first step is the usual slip. Reread the question to check you finished."),
  ("unknown number", "The number you are missing. A letter or a box can stand in for it.",
   "Ivy sees 12 - ? = 7. She asks herself what takes 12 down to 7. The unknown number is 5.",
   ""),
 ],
 "NBT": [
  ("hundreds", "Groups of one hundred.",
   "Zoe counts 342 pennies. She stacks them and finds 3 hundreds, 4 tens, and 2 ones.",
   ""),
  ("expanded form", "A number written as the sum of what each digit is worth.",
   "Theo writes 254 in expanded form: 200 + 50 + 4.",
   ""),
  ("place value", "What a digit is worth based on its spot.",
   "Nina looks at 528. The 5 sits in the hundreds place, so it is worth 500.",
   ""),
  ("regroup", "Trade ten of one unit for one of the next unit.",
   "Omar adds 27 + 15. The ones make 12. He regroups 10 of them into 1 ten and writes 42.",
   ""),
  ("compare numbers", "Decide which number is bigger by checking place value.",
   "Maya compares 431 and 419. The hundreds match, so she checks the tens. 3 beats 1, so 431 is bigger.",
   "More digits usually means bigger, but only when you start from the biggest place. Compare left to right."),
 ],
 "MD": [
  ("centimeter", "A small unit of length. It is about as wide as your fingernail.",
   "Leo lays his crayon along a ruler. The crayon is 9 centimeters long.",
   ""),
  ("meter", "A larger unit of length. It is about as wide as a door.",
   "Ana measures the rug with a meter stick. She steps it out twice, so the rug is 2 meters long.",
   ""),
  ("estimate", "A smart guess that is close, not exact.",
   "Ben looks at a jar of beans and guesses about 50. The real count is 46, so his estimate was close.",
   "An estimate is not a wild guess. Use what you know to get near the real amount."),
  ("number line", "A line with numbers spaced out in order.",
   "Ivy starts at 8 on the number line and hops to 13. She counts 5 hops.",
   ""),
  ("bar graph", "A graph that uses bars to show amounts.",
   "Zoe makes a bar graph of favorite fruits. The apple bar rises highest, so apples won.",
   ""),
  ("picture graph", "A graph that uses pictures to stand for amounts.",
   "Theo draws a picture graph of books read. Each little book stands for 1 real book.",
   ""),
  ("line plot", "A graph that stacks marks above a number line.",
   "Nina measures 10 leaves and marks an X above each length. Most of the X's stack above 4 centimeters.",
   ""),
  ("dollar", "A unit of money worth 100 cents.",
   "Omar saves 4 quarters in a jar. Together they make 1 dollar.",
   ""),
  ("quarter (coin)", "A coin worth 25 cents.",
   "Maya has 3 quarters. She counts 25, 50, 75. She has 75 cents.",
   ""),
 ],
 "G": [
  ("quadrilateral", "A closed shape with 4 straight sides.",
   "Leo sorts his shape cards. The square, the rectangle, and the kite all go in one pile. Each has 4 sides.",
   ""),
  ("pentagon", "A closed shape with 5 straight sides.",
   "Ana traces home plate at the ball field. She counts 5 sides, so it is a pentagon.",
   ""),
  ("rows and columns", "Rows go across. Columns go up and down.",
   "Ben sets up chairs in 4 rows and 6 columns. He counts 24 chairs in all.",
   ""),
  ("equal shares", "Parts of one whole that are all the same size.",
   "Ivy cuts a brownie into 4 equal shares. Each friend gets a piece the same size.",
   ""),
 ],
},
"3": {
 "OA": [
  ("multiply", "Add equal groups the fast way.",
   "Zoe packs 6 boxes with 4 markers in each. Instead of adding six times, she multiplies 6 × 4 and gets 24.",
   ""),
  ("factor", "A number you multiply.",
   "Theo writes 3 × 8 = 24. The 3 and the 8 are the factors.",
   ""),
  ("product", "The answer when you multiply.",
   "Nina multiplies 5 × 7. The product is 35.",
   ""),
  ("divide", "Split into equal groups.",
   "Omar has 12 grapes and 3 friends. He divides them evenly, so each friend gets 4.",
   ""),
  ("quotient", "The answer when you divide.",
   "Maya divides 20 by 4. The quotient is 5.",
   ""),
  ("equal groups", "Groups that all hold the same amount.",
   "Leo sorts 15 crayons into 3 equal groups. Each group holds 5 crayons.",
   ""),
  ("array", "Objects in equal rows and columns. It shows a multiplication fact.",
   "Ana draws 4 rows of 6 dots. Her array shows 4 × 6 = 24.",
   ""),
  ("area model", "A rectangle drawing that shows a multiplication problem.",
   "Ben draws a rectangle 3 units tall and 5 units wide. He counts 15 squares inside. His area model shows 3 × 5 = 15.",
   ""),
  ("unknown factor", "The missing number in a multiplication fact.",
   "Ivy sees 4 × ? = 28. She counts by fours until she reaches 28. The unknown factor is 7.",
   ""),
 ],
 "NBT": [
  ("round", "Change a number to a nearby easier one.",
   "Zoe rounds 47 to the nearest ten. On the number line 47 sits closer to 50 than to 40, so she rounds up.",
   "Look at where the number really sits. Do not just chop the last digit off."),
  ("place value", "What a digit is worth because of its spot.",
   "Theo looks at 528. The 2 sits in the tens place, so it is worth 20.",
   ""),
 ],
 "NF": [
  ("fraction", "A number that names part of a whole.",
   "Nina cuts a pie into 4 equal slices and takes 1. She ate 1/4 of the pie.",
   "The parts have to be equal. Four uneven slices do not make fourths."),
  ("numerator", "The top number. It counts the parts you have.",
   "Omar eats 3 slices out of 8. He writes 3/8. The numerator 3 is how many he ate.",
   ""),
  ("denominator", "The bottom number. It tells how many equal parts make the whole.",
   "Maya writes 3/8. The denominator 8 means the whole pie was cut into 8 equal parts.",
   ""),
  ("unit fraction", "A fraction with 1 on top. It is one single part.",
   "Leo cuts a ribbon into 5 equal pieces and picks up one. He holds 1/5, a unit fraction.",
   ""),
  ("equivalent fractions", "Different fractions that name the same amount.",
   "Ana eats 1/2 of a pizza. Ben eats 2/4 of a pizza the same size. They both ate the same amount.",
   ""),
  ("whole", "All of the parts together. One complete thing.",
   "Ivy has 4 quarter slices of an orange. Put back together they make one whole orange.",
   ""),
  ("partition", "Split something into equal parts.",
   "Zoe partitions a paper strip into 6 equal parts. Now each part is 1/6 of the strip.",
   ""),
  ("compare fractions", "Decide which fraction is larger.",
   "Theo compares 1/3 and 1/5 of the same cake. Fewer slices means bigger slices, so 1/3 is more.",
   "A bigger bottom number does not mean a bigger piece. It means the whole was cut into more, smaller parts."),
 ],
 "MD": [
  ("area", "The amount of flat space a shape covers.",
   "Nina tiles a table top with square tiles. She counts 24 tiles, so the area is 24 square units.",
   "Area is the space inside. Perimeter is the trip around the edge."),
  ("perimeter", "The distance all the way around a shape.",
   "Omar walks around a square garden. Each side takes 5 steps, so the perimeter is 20 steps.",
   ""),
  ("square unit", "One square used to measure area.",
   "Maya covers a card with squares, leaving no gaps. Each one is a square unit. She counts 12.",
   ""),
  ("elapsed time", "How much time has passed.",
   "Leo starts reading at 2:00 and stops at 2:45. The elapsed time is 45 minutes.",
   ""),
  ("liquid volume", "How much liquid a container holds.",
   "Ana fills a bottle from the jug. The bottle holds 1 liter, so that is its liquid volume.",
   ""),
  ("mass", "How much matter is in an object.",
   "Ben sets an apple on the scale. Its mass is 150 grams.",
   ""),
  ("scaled graph", "A graph where one picture or step stands for more than one thing.",
   "Ivy makes a graph where each square stands for 5 books. A bar 4 squares tall means 20 books.",
   "Count the value of each step, not the number of steps."),
 ],
 "G": [
  ("quadrilateral", "A closed shape with exactly 4 straight sides.",
   "Zoe drops shapes into a hoop labeled 4 sides. Squares, rectangles, and rhombuses all belong.",
   ""),
  ("category", "A group whose members share a trait.",
   "Theo makes a category for shapes with 4 sides. The square and the rectangle both belong in it.",
   ""),
  ("attribute", "A feature of a shape you can name.",
   "Nina looks at a rectangle. She names two attributes. It has 4 square corners, and the sides across from each other match.",
   ""),
 ],
},
"4": {
 "OA": [
  ("factor", "A number that divides into another with nothing left over.",
   "Omar tests 12. He finds 1, 2, 3, 4, 6, and 12 all divide it evenly. Those are the factors of 12.",
   ""),
  ("multiple", "What you get when you multiply a number by a whole number.",
   "Maya skip counts by 4: 4, 8, 12, 16. Each number she lands on is a multiple of 4.",
   "Factors are smaller and divide in. Multiples are bigger and count up."),
  ("prime number", "A number with exactly two factors: 1 and itself.",
   "Leo tries to split 7 counters into equal groups. Only 1 group of 7 works. So 7 is prime.",
   "The number 1 is not prime. It has only one factor, not two."),
  ("composite number", "A number with more than two factors.",
   "Ana splits 12 counters into 2 groups of 6, then into 3 groups of 4. Many splits work, so 12 is composite.",
   ""),
  ("multi-step problem", "A problem that needs more than one step.",
   "Ben buys 3 packs of 8 pencils, then gives 5 away. First he multiplies to get 24. Then he subtracts to get 19.",
   ""),
  ("remainder", "The amount left over after dividing.",
   "Ivy shares 17 stickers with 5 friends. Each one gets 3, and the remainder is 2.",
   ""),
  ("variable", "A letter that stands for a number you do not know yet.",
   "Zoe writes 6 × n = 42. The letter n is the variable. She solves it and finds n = 7.",
   ""),
 ],
 "NBT": [
  ("place value", "What each digit is worth based on its position.",
   "Theo studies 5,283. The 5 sits in the thousands place, so it is worth 5,000.",
   ""),
  ("multi-digit", "A number with more than one digit.",
   "Nina adds 3,472 and 1,915. Both are multi-digit numbers, so she lines up the places before she starts.",
   ""),
  ("standard algorithm", "The usual step by step way to work a problem on paper.",
   "Omar multiplies 34 × 26. He uses the standard algorithm, working one place at a time and carrying when needed.",
   ""),
 ],
 "NF": [
  ("equivalent fraction", "A fraction that names the same amount as another.",
   "Maya has 2/4 of a chocolate bar. Leo has 1/2 of the same bar. Their pieces are exactly the same size.",
   ""),
  ("mixed number", "A whole number joined with a fraction.",
   "Ana pours 2 full glasses of juice and half of a third. She has 2 1/2 glasses.",
   ""),
  ("improper fraction", "A fraction whose top number is bigger than its bottom.",
   "Ben has 5 quarter slices of pie. He writes 5/4, which is more than one whole pie.",
   "An improper fraction is not wrong. It is just written as parts instead of wholes."),
  ("common denominator", "A shared bottom number for two fractions.",
   "Ivy adds 1/3 and 1/4. She rewrites them as 4/12 and 3/12. Now they share a denominator, so she can add.",
   ""),
  ("decimal", "A number that uses a dot to show parts smaller than one.",
   "Zoe reads a price tag: $2.75. The dot separates the whole dollars from the cents.",
   ""),
  ("tenths", "One whole split into 10 equal parts.",
   "Theo shades 3 strips out of 10. He shaded 3 tenths, which he writes as 0.3.",
   ""),
  ("hundredths", "One whole split into 100 equal parts.",
   "Nina shades 25 little squares on a grid of 100. She shaded 25 hundredths, or 0.25.",
   ""),
  ("benchmark fraction", "A well known fraction you use to judge others.",
   "Omar wonders how big 5/8 is. He compares it to 1/2, a benchmark. 5/8 is a little more than half.",
   ""),
 ],
 "MD": [
  ("angle", "The corner shape made where two rays meet.",
   "Maya opens a pair of scissors. The space between the blades forms an angle.",
   "Longer arms do not make a bigger angle. Only the spread between them counts."),
  ("degree", "The unit used to measure an angle.",
   "Leo measures a square corner with his protractor. It reads 90 degrees.",
   ""),
  ("protractor", "A tool for measuring angles.",
   "Ana lines up the middle of her protractor with the corner. She reads 45 degrees.",
   ""),
  ("perimeter", "The total distance around the outside of a shape.",
   "Ben fences a garden 8 feet by 3 feet. He adds 8 + 3 + 8 + 3 and needs 22 feet of fence.",
   ""),
  ("formula", "A rule written with symbols that works every time.",
   "Ivy uses the formula for area: length × width. Her rug is 6 by 4, so the area is 24.",
   ""),
  ("conversion", "Changing a measure into a different unit.",
   "Zoe has 3 feet of ribbon and needs inches. She multiplies 3 × 12 and gets 36 inches.",
   ""),
 ],
 "G": [
  ("point", "An exact spot. It has no size at all.",
   "Theo marks a dot on the map where the library sits. That dot is a point.",
   ""),
  ("line", "A straight path that goes on forever both ways.",
   "Nina draws a straight path and puts an arrow on each end. The arrows show the line never stops.",
   ""),
  ("ray", "A straight path with one end. It goes on forever the other way.",
   "Omar shines a flashlight. The beam starts at the bulb and keeps going, much like a ray.",
   ""),
  ("acute angle", "An angle smaller than a square corner.",
   "Maya opens a book just a crack. The narrow angle at the spine is acute.",
   ""),
  ("obtuse angle", "An angle bigger than a square corner.",
   "Leo leans a chair back until it nearly lies flat. The wide angle it makes is obtuse.",
   ""),
  ("right angle", "A square corner. It measures 90 degrees.",
   "Ana checks the corner of her paper against a tile. They match exactly, so it is a right angle.",
   ""),
  ("parallel lines", "Lines that stay the same distance apart and never meet.",
   "Ben looks down the train tracks. The rails run side by side forever, so they are parallel.",
   ""),
  ("perpendicular lines", "Lines that cross and make a square corner.",
   "Ivy studies the window frame. The upright meets the sill at a square corner, so those lines are perpendicular.",
   ""),
  ("line of symmetry", "A line that folds a shape into two matching halves.",
   "Zoe folds a paper heart down the middle. The two halves match exactly, so the fold is a line of symmetry.",
   "Not every fold works. The halves have to land on each other exactly."),
 ],
},
"5": {
 "OA": [
  ("order of operations", "The agreed order for working a problem. Do parentheses first. Then multiply and divide. Add and subtract last.",
   "Theo solves 2 + 3 × 4. He multiplies first and gets 12. Then he adds 2 for a total of 14.",
   "Working left to right gives 20 here, which is wrong. Multiplying comes before adding."),
  ("parentheses", "Curved marks that show what to work out first.",
   "Nina solves (2 + 3) × 4. The parentheses come first, so she gets 5. Then 5 × 4 gives 20.",
   ""),
  ("expression", "A math phrase with numbers and signs. It has no equal sign.",
   "Omar writes 6 × (2 + 1). That is an expression, not an equation.",
   ""),
  ("evaluate", "Work out what an expression is worth.",
   "Maya evaluates 4 × (3 + 2). Inside the parentheses gives 5. Then 4 × 5 gives 20.",
   ""),
  ("numerical pattern", "A list of numbers that follows a rule.",
   "Leo starts at 3 and adds 5 each time: 3, 8, 13, 18. His pattern grows by 5.",
   ""),
  ("coordinate pair", "Two numbers that locate a point on a grid.",
   "Ana plots (4, 3). She moves 4 across, then 3 up, and marks the spot.",
   ""),
 ],
 "NBT": [
  ("exponent", "A small raised number. It tells how many times to multiply the base by itself.",
   "Ben writes 10 with a small 3 above it. The exponent means 10 × 10 × 10, which is 1,000.",
   "An exponent is not the same as multiplying by 3. It means three tens multiplied together."),
  ("power of ten", "What you get when you multiply 10 by itself.",
   "Ivy sees that 100 is 10 × 10. That makes 100 a power of ten.",
   ""),
  ("round decimals", "Change a decimal to a nearby simpler one.",
   "Zoe rounds 3.67 to the nearest tenth. The 7 pushes it up, so she writes 3.7.",
   ""),
  ("multiply decimals", "Multiply as you would whole numbers. Then place the dot.",
   "Theo multiplies 0.4 × 0.3. He thinks 4 × 3 = 12. Two decimal places give him 0.12.",
   "The answer can be smaller than what you started with. Multiplying by a part shrinks it."),
  ("divide decimals", "Split a decimal into equal parts.",
   "Nina pours 4.5 liters into 3 bottles evenly. Each bottle gets 1.5 liters.",
   ""),
 ],
 "NF": [
  ("common denominator", "A shared bottom number that lets you add or compare fractions.",
   "Omar adds 1/2 and 1/3. He rewrites them as 3/6 and 2/6, then adds to get 5/6.",
   "You cannot add the bottom numbers. Make them match first, then add only the tops."),
  ("mixed number", "A whole number plus a fraction.",
   "Maya runs 3 whole laps and half of another. She ran 3 1/2 laps.",
   ""),
  ("multiply fractions", "Multiply the top numbers. Then multiply the bottom numbers.",
   "Leo scoops 1/2 of a 1/3 cup measure. He multiplies and finds he has 1/6 of a cup.",
   ""),
  ("divide fractions", "Split a fraction into equal parts, or find how many fit inside.",
   "Ana has 1/2 a pizza and shares it with 2 people. Each one gets 1/4 of the pizza.",
   ""),
  ("simplify", "Write a fraction with the smallest numbers that still name the same amount.",
   "Ben has 6/8 of a bar. He divides the top and bottom by 2 and writes 3/4.",
   ""),
  ("reciprocal", "The fraction you get when you flip one over.",
   "Ivy flips 2/5 and gets 5/2. That is the reciprocal. The two of them multiply to 1.",
   ""),
 ],
 "MD": [
  ("volume", "The amount of space a solid takes up.",
   "Zoe fills a box with unit cubes. It holds 3 layers of 8, so the volume is 24 cubic units.",
   "Volume fills the inside. Area only covers a flat surface."),
  ("cubic unit", "One cube used to measure volume.",
   "Theo stacks cubes inside a box with no gaps. Each cube is one cubic unit, and he counts 18.",
   ""),
  ("convert units", "Change a measure to a different unit.",
   "Nina has 2,000 meters left to run. She converts it and sees that is just 2 kilometers.",
   ""),
  ("coordinate plane", "A grid made by two number lines that cross.",
   "Omar maps his neighborhood on a coordinate plane. He finds the park at (4, 3).",
   ""),
  ("x-axis", "The number line that runs across the grid.",
   "Maya moves right along the x-axis to 5 before she moves up at all.",
   ""),
  ("y-axis", "The number line that runs up and down the grid.",
   "Leo counts up the y-axis to 4 to finish plotting his point.",
   ""),
 ],
 "G": [
  ("coordinate plane", "A grid for locating points. A level line and an upright line cross to make it.",
   "Ana plots (4, 3) on the coordinate plane. She goes 4 across, then 3 up.",
   ""),
  ("ordered pair", "Two numbers in order that give a point's spot. The across number comes first.",
   "Ben plots (2, 5). He moves 2 across, then 5 up. The order changes where he lands.",
   "Swapping the numbers lands you somewhere else. (2, 5) is not the same as (5, 2)."),
  ("classify", "Sort shapes into groups by what they have in common.",
   "Ivy classifies triangles by their angles. She makes one pile each for acute, right, and obtuse.",
   ""),
  ("hierarchy of shapes", "A way to order shape groups. Smaller groups fit inside bigger ones.",
   "Zoe draws a chart of shapes. Squares fit inside rectangles, and rectangles fit inside quadrilaterals.",
   "Every square is a rectangle, but not every rectangle is a square."),
 ],
},
}


def slugify(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower())
    return value.strip("-")


def build_entries() -> list[dict]:
    entries = []
    for grade, domains in DATA.items():
        for dcode, terms in domains.items():
            for term, definition, example, misconception in terms:
                entries.append({
                    "id": slugify(f"{grade}-{dcode}-{term}"),
                    "term": term,
                    "grade": grade,
                    "domainCode": dcode,
                    "domain": DOMAIN_NAMES[dcode],
                    "standard": f"{grade}.{dcode}",
                    "definition": definition,
                    "example": example,
                    "misconception": misconception,
                })
    return entries


def write_markdown(out_dir: str) -> None:
    """Per-grade Markdown: the human-readable, git-friendly source of truth."""
    md_dir = os.path.join(out_dir, "vocab_bank")
    os.makedirs(md_dir, exist_ok=True)
    for grade, domains in DATA.items():
        lines = [f"# Grade {grade} Math Vocabulary\n"]
        for dcode, terms in domains.items():
            lines.append(f"\n## {DOMAIN_NAMES[dcode]} ({grade}.{dcode})\n")
            for term, definition, example, misconception in terms:
                lines.append(f"### {term}\n")
                lines.append(f"**Definition:** {definition}\n")
                lines.append(f"**Example:** {example}\n")
                if misconception:
                    lines.append(f"**Common misconception:** {misconception}\n")
        with open(os.path.join(md_dir, f"grade-{grade}.md"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines))


def main() -> None:
    out_dir = os.path.dirname(os.path.abspath(__file__))
    entries = build_entries()

    ids = [e["id"] for e in entries]
    duplicates = {i for i in ids if ids.count(i) > 1}
    if duplicates:
        raise SystemExit(f"Duplicate term ids: {sorted(duplicates)}")

    with open(os.path.join(out_dir, "vocab_data.json"), "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)

    write_markdown(out_dir)

    print(f"Wrote {len(entries)} terms across {len(DATA)} grades.")
    print("Markdown files written to vocab_bank/")
    readability.report(entries)


if __name__ == "__main__":
    main()
